### ISSUE TITLE
Crash on -g on movies only channel

### ISSUE THREAD

**Issue by MoeFwacky** [justinemter/pseudo-channel#54]
I've had this happen when running `-g` on my movies channel pretty reliably today.  (Note: my schedule runs 5am to 5am, so after midnight doesn't spill into the next "day")

```
++++ There is overlap. Setting new time-interval: 1900-01-01 23:15:00
++++ New start time: 11:15:00 PM
#### Adding media to db: mullinax-easter-1993 11:11:23 PM
#### Adding media to db: crest-1994 11:12:03 PM
#### Adding media to db: kmart-cordlessphone-1987 11:12:43 PM
#### Adding media to db: thesting 11:13:08 PM
#### Adding media to db: V for Vendetta 11:15:00 PM
++++ NOT strict-time: End of Days
++++ Previous End Time:  01:27:32 AM Intended start time:  12:30:00 AM
Traceback (most recent call last):
  File "PseudoChannel.py", line 732, in <module>
    pseudo_channel.generate_daily_schedule()
  File "PseudoChannel.py", line 515, in generate_daily_schedule
    previous_episode.overlap_max
  File "PseudoChannel.py", line 341, in calculate_start_time
    return newStartTime.strftime('%I:%M:%S %p')
AttributeError: 'str' object has no attribute 'strftime'
```

**Comment by justinemter** [comment]
I've gotten this too. I cannot figure out the exact cause so instead I am going to let it fail silently. I am telling you this because if you see something strange moving forward we know where to look...

**Comment by justinemter** [comment]
So far so good on my end! I'm going to keep this open until we know for sure.

**Comment by justinemter** [comment]
Closing this as it doesn't seem to be affecting anything anymore.
